"""
GitHooks - Git钩子集成

功能:
- 自动安装Git钩子
- post-commit钩子: 提交后自动触发进化分析
- pre-commit钩子: 提交前检查

使用方式:
    from quickagents import GitHooks

    hooks = GitHooks()
    hooks.install()  # 安装钩子
    hooks.uninstall()  # 卸载钩子
"""

import os
import stat
import sys
from pathlib import Path
from typing import Dict


class GitHooks:
    """
    Git钩子管理器

    使用方式:
        hooks = GitHooks()

        # 安装所有钩子
        hooks.install()

        # 仅安装post-commit
        hooks.install_post_commit()

        # 卸载
        hooks.uninstall()
    """

    def __init__(self, repo_path: str = "."):
        """
        初始化

        Args:
            repo_path: Git仓库路径
        """
        self.repo_path = Path(repo_path).resolve()
        self.git_dir = self.repo_path / ".git"
        self.hooks_dir = self.git_dir / "hooks"
        self.log_dir = self.repo_path / ".quickagents" / "hooks"
        self.log_file = self.log_dir / "post-commit.log"

    def _generate_python_hook(self) -> str:
        """Generate the shared Python hook script"""
        python_exec = sys.executable.replace("\\", "/")
        log_file_posix = str(self.log_file).replace("\\", "/")
        return f"""import sys
import os
import datetime

sys.path.insert(0, os.getcwd())
log_file = r"{log_file_posix}"

def log_error(msg):
    try:
        os.makedirs(os.path.dirname(log_file), exist_ok=True)
        with open(log_file, "a") as f:
            f.write(f"{{datetime.datetime.now().isoformat()}} ERROR: {{msg}}\\n")
    except Exception:
        pass

commit_hash = os.environ.get("QA_COMMIT_HASH", "unknown")
commit_msg = os.environ.get("QA_COMMIT_MSG", "")
files_changed_str = os.environ.get("QA_FILES_CHANGED", "")
files_changed = [f for f in files_changed_str.split(",") if f]

try:
    from quickagents.core.unified_db import UnifiedDB
    from quickagents.core.evolution import SkillEvolution

    db = UnifiedDB()
    evolution = SkillEvolution(db)
    evolution.on_git_commit({{
        "hash": commit_hash,
        "message": commit_msg,
        "files_changed": files_changed,
    }})
except Exception as e:
    log_error(f"Evolution failed: {{e}}")

try:
    from quickagents.audit import AuditGuard
    guard = AuditGuard()
    guard.on_git_commit(staged_files=files_changed)
except Exception as e:
    log_error(f"AuditGuard failed: {{e}}")
"""

    def _generate_bash_hook(self) -> str:
        """Generate bash hook for Unix / Git Bash"""
        return r"""#!/bin/bash
# QuickAgents post-commit hook
# Auto-generated by qka hooks install

COMMIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
COMMIT_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "")
FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD 2>/dev/null | tr '\n' ',' | sed 's/,$//')

if command -v python3 &>/dev/null; then
    PYTHON_CMD="python3"
elif command -v python &>/dev/null; then
    PYTHON_CMD="python"
else
    exit 0
fi

LOG_FILE=".quickagents/hooks/post-commit.log"
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null

export QA_COMMIT_HASH="$COMMIT_HASH"
export QA_COMMIT_MSG="$COMMIT_MSG"
export QA_FILES_CHANGED="$FILES_CHANGED"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
$PYTHON_CMD "$SCRIPT_DIR/post-commit.py" 2>>"$LOG_FILE"

exit 0
"""

    def _generate_windows_hook(self) -> str:
        """Generate Windows-compatible batch wrapper"""
        return r"""@echo off
REM QuickAgents post-commit hook (Windows wrapper)
REM Auto-generated by qka hooks install

set "COMMIT_HASH="
for /f "delims=" %%i in ('git rev-parse HEAD 2^>nul') do set "COMMIT_HASH=%%i"
if not defined COMMIT_HASH set "COMMIT_HASH=unknown"

set "COMMIT_MSG="
for /f "delims=" %%i in ('git log -1 --pretty=%%s 2^>nul') do set "COMMIT_MSG=%%i"

set "FILES_CHANGED="
for /f "delims=" %%i in ('git diff-tree --no-commit-id --name-only -r HEAD 2^>nul') do (
    if defined FILES_CHANGED (
        set "FILES_CHANGED=!FILES_CHANGED!,%%i"
    ) else (
        set "FILES_CHANGED=%%i"
    )
)

setlocal enabledelayedexpansion
set "PYTHON_CMD=python"
where python3 >nul 2>nul && set "PYTHON_CMD=python3"

set "LOG_FILE=.quickagents\hooks\post-commit.log"
if not exist ".quickagents\hooks" mkdir ".quickagents\hooks"

set "QA_COMMIT_HASH=%COMMIT_HASH%"
set "QA_COMMIT_MSG=%COMMIT_MSG%"
set "QA_FILES_CHANGED=%FILES_CHANGED%"

set "SCRIPT_DIR=%~dp0"
"%PYTHON_CMD%" "%SCRIPT_DIR%post-commit.py" 2>>"%LOG_FILE%"

endlocal
exit /b 0
"""

    def is_git_repo(self) -> bool:
        """检查是否是Git仓库"""
        return self.git_dir.exists()

    def _backup_hook(self, hook_path: Path) -> bool:
        """备份现有钩子"""
        if not hook_path.exists():
            return False
        backup_path = hook_path.with_suffix(".backup")
        if not backup_path.exists():
            hook_path.rename(backup_path)
            return True
        return False

    def install(self) -> Dict[str, bool]:
        """
        安装所有钩子

        Returns:
            安装结果
        """
        if not self.is_git_repo():
            return {"error": "Not a git repository"}  # type: ignore[dict-item]

        result = {"post_commit": self.install_post_commit()}

        return result

    def install_post_commit(self) -> bool:
        """
        安装post-commit钩子

        生成三个文件:
        - post-commit (bash, for Unix / Git Bash)
        - post-commit.cmd (batch, for Windows CMD)
        - post-commit.py (shared Python logic)

        Returns:
            是否成功
        """
        if not self.is_git_repo():
            return False

        self.hooks_dir.mkdir(parents=True, exist_ok=True)
        self.log_dir.mkdir(parents=True, exist_ok=True)

        for name in ("post-commit", "post-commit.cmd", "post-commit.py"):
            self._backup_hook(self.hooks_dir / name)

        (self.hooks_dir / "post-commit.py").write_text(self._generate_python_hook(), encoding="utf-8")

        bash_path = self.hooks_dir / "post-commit"
        bash_path.write_text(self._generate_bash_hook(), encoding="utf-8")
        try:
            bash_path.chmod(bash_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        except OSError:
            pass

        (self.hooks_dir / "post-commit.cmd").write_text(self._generate_windows_hook(), encoding="utf-8")

        return True

    def uninstall(self) -> Dict[str, bool]:
        """
        卸载所有钩子

        Returns:
            卸载结果
        """
        result = {}
        had_hooks = False

        for name in ("post-commit", "post-commit.cmd", "post-commit.py"):
            hook_path = self.hooks_dir / name
            if hook_path.exists():
                hook_path.unlink()
                had_hooks = True

        if had_hooks:
            result["post_commit"] = True

            backup_path = self.hooks_dir / "post-commit.backup"
            if backup_path.exists():
                target = self.hooks_dir / "post-commit"
                backup_path.rename(target)
                result["post_commit_restored"] = True

        return result

    def get_status(self) -> Dict:
        """
        获取钩子状态

        Returns:
            状态信息
        """
        return {
            "is_git_repo": self.is_git_repo(),
            "hooks_dir_exists": self.hooks_dir.exists(),
            "post_commit_installed": (self.hooks_dir / "post-commit").exists(),
            "post_commit_cmd_installed": (self.hooks_dir / "post-commit.cmd").exists(),
            "post_commit_py_installed": (self.hooks_dir / "post-commit.py").exists(),
            "post_commit_has_backup": (self.hooks_dir / "post-commit.backup").exists(),
        }
